MentorMate/node-project-cli

assets/.eslintignore, assets/.prettierignore, assets/.project-gitignr, assets/.project-npmignr, assets/jest.config.ts.js, assets/jest.config.vanilla.js, assets/local-scripts/initiate-detect-secrets.sh, assets/scripts/dockerize.sh, assets/src/api/sample-module/interfaces/index.ts, assets/src/api/sample-module/v1/__data__/input.json, assets/src/api/sample-module/v1/__data__/output.json, assets/src/api/sample-module/v1/helpers/__data__/input.json, assets/src/api/sample-module/v1/helpers/__data__/output.json, assets/src/api/sample-module/v1/samples.controller.test.ts, assets/src/api/sample-module/v1/samples.controller.ts, assets/src/api/sample-module/v1/samples.service.test.ts, assets/src/api/sample-module/v1/samples.service.ts, assets/src/database/interfaces/index.ts, assets/src/database/models/index.ts, assets/src/database/models/sample.model.ts, assets/src/helpers/index.ts, assets/test/index.ts, assets/tsconfig.json, src/commands/generate.js, src/templates/eslintrc-model.js.ejs
- Addresses https://github.com/MentorMate/node-pipeline-template/issues/4
- Addresses https://github.com/MentorMate/node-pipeline-template/issues/6
- Addresses https://github.com/MentorMate/node-pipeline-template/issues/7
- Addresses https://github.com/MentorMate/node-pipeline-template/issues/10
- Addresses https://github.com/MentorMate/node-pipeline-template/issues/11
=> Fix initial reported issues

src/extensions/install-framework.js, src/extensions/install-framework.test.js, src/extensions/ts-setup.js, src/extensions/ts-setup.test.js, src/templates/nodemon/nodemon.json.ejs
=> feat(live-reload): implement live reload via nodemon

assets/dotenv/.env.example, assets/express/src/index.ts, src/extensions/install-framework.js
Added some boilerplate around:
=> chore: boilerplate to ease discussion

assets/express/src/index.ts, src/extensions/install-framework.js, src/extensions/install-framework.test.js
=> feat(errors): add http specific error handling

assets/express/src/index.ts, assets/tsconfig.json, src/extensions/install-framework.js, src/extensions/install-framework.test.js
Starting the application will drop a `./swagger.json` file in order to inspect the output.
=> feat(docs): add openapi generation

assets/express/scripts/generate-openapi.ts, assets/express/src/app.ts, assets/express/src/common/environment.ts, assets/express/src/common/index.ts, assets/express/src/index.ts, assets/tsconfig.json
=> refactor: cleanup entry points

assets/vscode/launch.json, src/commands/generate.js, src/extensions/install-framework.js, src/extensions/install-framework.test.js, src/templates/README.md.ejs
=> docs: add a readme for the example app

assets/express/src/api/v1/todos/routes/create.ts, assets/express/src/api/v1/todos/routes/delete.ts, assets/express/src/api/v1/todos/routes/get.ts, assets/express/src/api/v1/todos/routes/list.ts, assets/express/src/api/v1/todos/routes/update.ts
=> fix: extend todo routes with unauthorized response

assets/express/src/api/auth/routes/login.ts, assets/express/src/api/healthz/ready.ts, assets/express/src/api/v1/todos/routes/create.ts, assets/express/src/api/v1/todos/routes/update.ts, assets/test/auth/login.spec-e2e.ts, assets/test/auth/register.spec-e2e.ts, assets/test/healthz/live.spec-e2e.ts, assets/test/healthz/ready.spec-e2e.ts, assets/test/jest-e2e.config.js, assets/test/todos/create.spec-e2e.ts, assets/test/todos/delete.spec-e2e.ts, assets/test/todos/get.spec-e2e.ts, assets/test/todos/list.spec-e2e.ts, assets/test/todos/update.spec-e2e.ts, assets/test/utils/create-todo.ts, assets/test/utils/get-random-number.ts, assets/test/utils/get-todo-payload.ts, assets/test/utils/get-user-credentials.ts, assets/test/utils/index.ts, assets/test/utils/register-user.ts, assets/test/utils/sortby-field-todos.ts
- Add e2e tests to cover health check, auth, todo endpoints
=> feat: e2e tests

assets/.prettierignore
=> chore(formatting): ignore coverage reports

README.md, src/commands/generate.js, src/extensions/install-framework.js, src/extensions/install-framework.test.js
=> chore: remove fastify choice

src/commands/generate.js, src/commands/generate.test.js, src/extensions/js-linters-extension.js, src/extensions/ts-setup.js, src/extensions/ts-setup.test.js, src/templates/eslintrc-model.js.ejs, src/utils/test/mocks.js
=> chore: remove es modules choice

assets/.github/workflows/audit.yaml, src/commands/generate.js, src/extensions/audit-workflow.js, src/extensions/audit-workflow.test.js, src/utils/test/mocks.js
=> feat: audit workflow

README.md, src/commands/generate.js, src/commands/generate.test.js, src/extensions/husky-setup-extension.test.js, src/utils/commands/example-app.config.js, src/utils/commands/questions.js, src/utils/test/mocks.js
=> feat: update cli app

src/commands/generate.js, src/extensions/generate-readme.js, src/extensions/husky-setup-extension.js, src/extensions/jest-config-and-coverage-wf.js
=> fix: nest e2e coverage

src/commands/generate.js, src/utils/commands/questions.js
=> fix: nest option in cli

src/commands/generate.js, src/extensions/generate-readme.js, src/templates/README.md.ejs
=> docs: add openapi instructions to readme.md

assets/express/example-app/__mocks__/knex.ts, assets/express/example-app/jest.config.js, assets/express/example-app/jest.setup.ts, assets/express/example-app/src/api/auth/routes/login.test.ts, assets/express/example-app/src/api/auth/routes/register.test.ts, assets/express/example-app/src/api/utils/response.test.ts, assets/express/example-app/src/api/v1/todos/routes/create.test.ts, assets/express/example-app/src/api/v1/todos/routes/delete.test.ts, assets/express/example-app/src/api/v1/todos/routes/get.test.ts, assets/express/example-app/src/api/v1/todos/routes/list.test.ts, assets/express/example-app/src/api/v1/todos/routes/update.test.ts, assets/express/example-app/src/common/openapi.test.ts, assets/express/example-app/test/auth/login.spec-e2e.ts, assets/express/example-app/test/auth/register.spec-e2e.ts, assets/express/example-app/test/healthz/live.spec-e2e.ts, assets/express/example-app/test/healthz/ready.spec-e2e.ts, assets/express/example-app/test/hello-world.spec-e2e.ts, assets/express/example-app/test/jest-e2e.config.js, assets/express/example-app/test/jest.setup.ts, assets/express/example-app/test/todos/create.spec-e2e.ts, assets/express/example-app/test/todos/delete.spec-e2e.ts, assets/express/example-app/test/todos/get.spec-e2e.ts, assets/express/example-app/test/todos/list.spec-e2e.ts, assets/express/example-app/test/todos/update.spec-e2e.ts, src/extensions/jest-config-and-coverage-wf.js, src/extensions/jest-config-and-coverage-wf.test.js
=> chore(tests): cleanup extension imports in test files

assets/nest/src/main.ts, src/extensions/install-nest.js, src/extensions/install-nest.test.js
=> fix: add cors to nest

src/extensions/install-nest.js, src/extensions/install-nest.test.js
=> fix: generate-nest-app

README.md
=> docs: update commitizen script in readme.md

src/extensions/install-framework.js
=> fix: volume path in openapi script

assets/db/pg/docker-compose.override.example.yml, assets/docker/ts/Dockerfile, assets/express/example-app/Dockerfile, assets/express/example-app/docker-compose.override.example.yml, assets/express/example-app/docker-compose.yml, assets/express/example-app/scripts/await-openapi-ui-start.sh, src/extensions/generate-readme.js, src/extensions/install-framework.js, src/extensions/install-framework.test.js, src/extensions/setup-postgresql.js, src/extensions/setup-postgresql.test.js, src/templates/README.md.ejs
=> fix: swagger ui

.lintstagedrc.js, README.md, assets/.lintstagedrc, docs/features.md, package-lock.json, package.json, src/extensions/js-linters-extension.js, src/extensions/js-linters-extension.test.js, src/templates/README.md.ejs
=> feat(lint): lint markdown

.eslintrc.js, assets/express/example-app/__mocks__/knex.ts, assets/express/example-app/src/app.ts, assets/express/example-app/src/utils/openapi.ts, assets/express/example-app/test/utils/sortby-field-todos.ts, package-lock.json, package.json, src/extensions/js-linters-extension.js, src/templates/eslintrc-model.js.ejs
=> feat(lint): add eslint-security

src/extensions/dockerize-workflow.js, src/extensions/dockerize-workflow.test.js, src/extensions/husky-setup-extension.js, src/extensions/husky-setup-extension.test.js, src/extensions/js-linters-extension.js, src/extensions/js-linters-extension.test.js, src/templates/husky/pre-commit.ejs
=> feat(lint): lint dockerfile

assets/.lintstagedrc, src/commands/generate.js, src/extensions/husky-setup-extension.js, src/extensions/husky-setup-extension.test.js, src/extensions/js-linters-extension.js, src/extensions/js-linters-extension.test.js, src/extensions/markdown-linter.js, src/extensions/markdown-linter.test.js, src/utils/commands/features.js, src/utils/commands/questions.js, src/utils/test/mocks.js
=> fix(nest): fix markdownlint setup

.husky/pre-commit, .husky/pre-push
=> chore(git-hooks): run tests on pre-commit

bin/node-cli, src/commands/generate.js, src/errors/command.error.js, src/extensions/create-project-directory.js, src/extensions/initialize-git.js
=> feat: improve error handling

src/commands/generate.js, src/extensions/command-help.js, src/utils/test/mocks.js
**P.S:** The idea is to have a configuration for the command options (rather than accessing the options in arbitrary places in the code base) and this is a preparation step.
=> feat: make command help dynamic

src/commands/generate.js, src/extensions/initialize-npm.js, src/extensions/initialize-npm.test.js, src/extensions/install-nest.js, src/extensions/install-nest.test.js, src/utils/test/mocks.js
=> chore: cleanup project scope option

README.md, src/commands/generate.js
Resolves: https://github.com/MentorMate/node-project-cli/issues/258
=> feat: add framework question for example apps

assets/nest/example-app/src/main.ts, assets/nest/example-app/src/utils/environment.ts, src/extensions/dockerize-workflow.js, src/extensions/dockerize-workflow.test.js, src/extensions/generate-readme.js, src/extensions/install-nest.js, src/extensions/install-nest.test.js, src/extensions/jest-config-and-coverage-wf.test.js, src/templates/README.md.ejs
- Fix readme generation and typos
- Delete Nest.js scripts and update the tests
- Remove swagger generation for production
- Fix Dockerfile issues with entrypoint and dependencies
=> Nest bugfixes and clean up

assets/nest/example-app-mongodb/src/utils/interceptors/request-logging.interceptor.ts, assets/nest/example-app-pg/src/utils/interceptors/request-logging.interceptor.ts
=> Fix/Nest Request Interceptor
